version: "3"

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: onix
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hcmus-tour
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cgbartg2qv267ufttkn0-a.singapore-postgres.render.com:5432/hcmustour
      SPRING_DATASOURCE_USERNAME: onix
      SPRING_DATASOURCE_PASSWORD: yrXTGErVv8NYIxn5Af6TvGPoOL3Ovl50
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  postgres-data: